import Head from "next/head";
import HomeMain from "../components/HomeMain/index";
import CallUs from "./../components/CallUs/index";
import StatusBars from "./../components/StatusBars/index";

export default function Home() {
    return (
        <>
            <Head>
                {/* <title>Create Next App</title> */}
                {/* <meta name="description" content="Generated by create next app" /> */}
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <main>
                <HomeMain />
                <StatusBars />
            </main>
            <CallUs />
        </>
    );
}
